# Generated by Django 4.1 on 2022-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="candidate", name="academic_details",),
        migrations.RemoveField(model_name="candidate", name="email",),
        migrations.RemoveField(model_name="candidate", name="last_name",),
        migrations.RemoveField(model_name="candidate", name="phone_no",),
        migrations.RemoveField(model_name="candidate", name="profesional_exp",),
        migrations.RemoveField(model_name="candidate", name="resume",),
        migrations.RemoveField(model_name="candidate", name="status",),
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
