# Generated by Django 4.1 on 2022-08-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_remove_candidate_academic_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="academic_details",
            field=models.TextField(default="asdsds"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="candidate",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="candidate",
            name="phone_no",
            field=models.CharField(default="12345678", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="profesional_exp",
            field=models.TextField(default="asdasd"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume",
            field=models.FileField(default="asds", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "applied"),
                    ("accepted", "accepted"),
                    ("rejected", "rejected"),
                ],
                default="applied",
                max_length=10,
            ),
        ),
    ]
