# Generated by Django 4.1 on 2022-08-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_candidate_academic_details_candidate_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="candidate", name="resume",),
    ]
