# Generated by Django 4.1 on 2022-08-24 07:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_remove_candidate_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone_no",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
