# Generated by Django 4.1 on 2022-08-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_alter_candidate_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone_no",
            field=models.CharField(max_length=10),
        ),
    ]
